### ISSUE TITLE
how to export data by using exportSparameters function?

### ISSUE THREAD

**Issue by Sarvesh178** [simos421/CST-MATLAB-API#10]
i want plots for for s11,s22,s21,s12 ...how to extract data and plot this data

**Comment by simos421** [comment]
Hi, please check MicrostripExample.m and you will find everything you need
there step by step.
I used this sequence to extract and plot the S11:

CstExportSparametersTXT(mws, exportpath)
[Frequency, Sparametter] = CstLoadSparametterTXT(filenameTXT);
plot(Frequency,Sparametter,'-'); grid on;
legend('S11 (dB)')
title('patch antenna at 2.45GHz')
xlabel('Frequency (GHz)')

For the s21 you will need any of my two port examples. For instance in
TwoDipolesExample.m i used this for the S11 & S21:

CstExportTouchstone(mws,exportpath, format)
data = read(rfdata.data,'NameofyourFile.s2p');
freq = data.Freq;
s_params = extract(data,'S_PARAMETERS',50);
spar = squeeze(s_params(1,:,:));
spar = spar';
sdb = 20*log10(sqrt(real(spar).^2 + imag(spar).^2));
S11 = sdb(:,1);
S21 = sdb(:,2);
figure
subplot(2,1,1)
plot(freq,S11); grid on;
title('S11')
subplot(2,1,2)
plot(freq,S21); grid on;
title('S21')

Thanks
Simos

**Comment by Sarvesh178** [comment]
Is there any way to export unit cell graph and image directly from cst to MATLAB...only the image ...in view option we do have export image option...but how to control from matlab by commands

**Comment by simos421** [comment]
Not sure what you mean, I suggest checking MetamaterialUnitCellExample.m.
Most probably you can do almost anything using matlab but you need to see
all my examples to have a better view of the basic functions and their
usability.
If you want to do something very specific that I haven't done yet, it's
very easy to do it yourself by following these steps:

1) first design what you want in CST, without using matlab
2) then, if you open the history log of CST you will see that it records
everything you did in visual basic script
3) Now you need to interface this script with matlab. So open one of my
functions (e.g. anything in the home folder of the api) and see how I
translate tha visual basic script into a matlab function. I use the invoke
function in matlab to do the visual basic to matlab translation.
It might look intimidating but it is very easy. Mostly just copy-paste

Thanks
Simos

**Comment by Sarvesh178** [comment]
Thank you sir for your response...i followed ur steps
1.Created unit cell
2.Checked history list wrote the code related to it
3. It's working..but when I tried to export image of unit cell...from view--------Export image in cst...it is getting exported and saved as image into my folder
4.but in history list export image command is not there to write function into my matlab code

**Comment by Sarvesh178** [comment]
I have to create Function code in matlab  that can export 3D view of my design (from Cst )to matlab  

All these figures have to save in folder...

**Comment by Sarvesh178** [comment]
Sir plz any replies

**Comment by simos421** [comment]
If it doesn't appear in the history it might not be possible to do it.
Maybe do that manually

**Comment by Sarvesh178** [comment]
Sir i found this link .... somehow useful ..and facing difficulty to incorporate into my code ....because i have adapted ur way style of writing the code by seeing ur examples..  any suggestions guidance would be really helpful regarding this..
https://in.mathworks.com/matlabcentral/fileexchange/72228-tcstinterface-cst-studio-suite-to-matlab-interface/?s_tid=LandingPageTabfx  ---- plz have a look once [Exporting geomertical moded from CST as an image]

**Comment by simos421** [comment]
Hi, If it doesn't appear in the history it might not be possible to do it.
Maybe do that manually
