### ISSUE TITLE
i am getting reshape error again and again when i am changing frequency range...?

### ISSUE THREAD

**Issue by Sarvesh178** [simos421/CST-MATLAB-API#11]
plz reply sir  i need help in this case

sir for different unit cells different frequency range is there S11 data is getting exported fine .....

sir i have to reshape the S11 values to 1 row multiple columns so that i can store S11 values to excel sheet

Sir in S11 ASCII file Data i checked there were 1001 rows 
So it was direct to use commands 
Sparameters=S11(:,2)
Reshape(Sparameters,[1,1001])

But when I am changing frequency range number of rows are getting increased to 1107...
 There is any way to control no of samples in frequencydomainsolverfunction

how it is possible?

**Comment by simos421** [comment]
Friend, this is simple matrix calculations in matlab. Just google it please
or ask your supervisor

**Comment by Sarvesh178** [comment]
plz check above comment There is any way to control no of samples in frequencydomainsolverfunction
