### ISSUE TITLE
is any way to export phase angle of Szmax(1),Zmax(1)

### ISSUE THREAD

**Issue by Sarvesh178** [simos421/CST-MATLAB-API#13]
i want to export phase angle of Szmax(1),Zmax(1)

**Comment by DickDiver** [comment]
I can't export the S-parameters as well. MATLAB displays "The ASCII export option is not available for the current view.". It looks like the "SelectTreeItem" code doesn't work. Don't know what to do : (

**Comment by Sarvesh178** [comment]
This error happens when we are not copying the syntax properly..the functions are well sufficient...to export ....if u r using frequency domain solver then u hv to write it / SZmax(1) ,Zmin(1). For time domain format is there in the function....

Simple way to check format.  Go to view in CST where u see Sparameters graph there at the bottom u can see format  /1D/. Something like this..

**Comment by DickDiver** [comment]
It worked, thank u so much! I didn't notice the syntax was different between frequency domain solver and time domain solver.  Sorry I cannot help you with your problem.

**Comment by Sarvesh178** [comment]
No prob ......i am glad it worked
