### ISSUE TITLE
hello Sir i really need help

### ISSUE THREAD

**Issue by Sarvesh178** [simos421/CST-MATLAB-API#15]
I am trying to export CST model as image from CST to matlab and store into  folder?
 but its not happening..
 hiw to invoke export image from cst

plz sir really need a help

**Comment by simos421** [comment]
You probably cannot do that. There is no such function in CST, meaning
there is no vba script behind it, meaning you cannot use the invoke matlab
function. Usually you just crop the image manually using lightshot or the
windows cropping tool. That's why.
Simos

**Comment by Sarvesh178** [comment]
Sir by my macro is it possible of save image?

**Comment by simos421** [comment]
No I don't think so

**Comment by Sarvesh178** [comment]
https://in.mathworks.com/matlabcentral/fileexchange/72228-tcstinterface-cst-studio-suite-to-matlab-interface


Sir in this code they are trying to export geometry...but it's really complicated


Ur guidance will be a great help  to me...
