### ISSUE TITLE
Issue when invoking some properties

### ISSUE THREAD

**Issue by SantaTitular** [simos421/CST-MATLAB-API#17]
Hi,

First of, thank you so much for these examples, it is very straighfoward and simple to follow! Was doing some more configurations that I need and, I'm trying to extrude a curve (or face but I cannot seem to pick the face even though I call the following: invoke(obj.mws,'Pick','PickFaceFromId', ['component', num2str(1),':','face', num2str(1)],'1');).

Anyways, I invoke the Extrude curve but, apparently, it does not recognize the "Thickness" and other parameters of the 'CoverCurve' (commented in the figure). Is this a problem with versions or something? I really cannot grasp what I'm missing
![image](https://user-images.githubusercontent.com/68435474/218616674-4066ab04-728b-409e-bafa-8d2bc63e640d.png)
![image](https://user-images.githubusercontent.com/68435474/218616718-e3e6d40c-ce54-45b9-9435-67a060ebcd0c.png)

Best,
Tomás

**Comment by SantaTitular** [comment]
Just to add aditional information, this is the macro I attain from just doing the operation in CST (2022)
![image](https://user-images.githubusercontent.com/68435474/218618109-675404ff-1523-4c81-8ef7-b73e440f1fc3.png)

**Comment by simos421** [comment]
Hello Tomas,
Thank you for your email. Using the pick command is tricky. I suggest doing
it manually first, together with your extrude command and then check the
CST History for the exact commands that appear there. Then translate these
commands in your code using the invoke function. That's always the best
solution for every troubleshooting. Alternatively use another strategy for
creating the geometry you want to create.
Thanks
Simos

**Comment by SantaTitular** [comment]
Hi Simos,

Thank you for the fast reply, apologies if you received an email with a previous response but I put the wrong images. I do agree with you that the best way to work with you method is trying in CST and then translating into MATLAB. I did manage to do the work around with Extrude Curve but the pick method seems very useful hence I'm trying to get it to work. 

Pick method:
**_CST Macros_**
![image](https://user-images.githubusercontent.com/68435474/218726524-8dad2eca-cf6b-47c4-815d-63b39efd3596.png)
![image](https://user-images.githubusercontent.com/68435474/218726588-7950d1e5-ff3c-4fa0-8fda-897362c33157.png)

**_MATLAB equivalent_**
![image](https://user-images.githubusercontent.com/68435474/218728379-f359ad4f-3233-4765-8a0f-8f865308e87e.png)
![image](https://user-images.githubusercontent.com/68435474/218728939-363826a3-c7a9-44fe-8631-9bcefd46bbfa.png)

Am I doing something wrong or do you know more in depth how to get the pick command to work, i.e., if I should propagate it into someplace?

**Comment by simos421** [comment]
What if instead of extrude you draw the geometry you want and either add it
to or subtract it from the surface you want?

**Comment by SantaTitular** [comment]
Hi Simos,

Apologies for the late reply, I actually got it to work. My goal was to generate the 3d surface from MATLAB in CST, this a workaround to that (for a 1D version). However, since I only know how to create and import .STL, I'll take the opportunity to ask you if you happen to know a way to draw the surface dynamically in MATLAB? For instance, connecting the points consecutively  using polygon3D so that when you cover, you actually get the surface, i.e., draw the surface the surface like you said.

Regarding the initial question, I managed to solved it with Pick. In case you happen to need in future situations: 
   - you can actually input the specified pick surface/component by adding an additional argument in Extrude (it is a minor detail but I guess important since there is no documentation available on CST), i.e.,
   PickFace = invoke(obj.mws,'Pick');
  invoke(PickFace,'PickFaceFromId', ['component', num2str(1),':','face', num2str(1)],'1');
  ExtrudeSurface = invoke(obj.mws,'Extrude','PickFace');
  ...
  invoke(ExtrudeSurface,'Create'); and release both
Note: For some reason the invoke does not work for commands if you concatenate them, e.g., Pick or Delete: invoke('Pick','PickFaceFromId', ['component', num2str(1),':','face', num2str(1)],'1');

In case you happen to know a easy way to generate the surface or the answer to the Note, lemme know!

Best,
Tomás

**Comment by SantaTitular** [comment]
Also, do you happen to know which parameter it is so that, when I delete, I do not get stuck in the window
![image](https://user-images.githubusercontent.com/68435474/218817696-d1570051-a944-4fc2-974c-2771355c2252.png)

The MATLAB macro is simply the following:
![image](https://user-images.githubusercontent.com/68435474/218817844-6c44fcfc-723f-40fa-aeff-db5650b0d4a3.png)

Apologies for continuously asking but this last one would be particularly helpful!

**Comment by simos421** [comment]
Hi Tomas,

It never got stuck on that window for me, I chose the first option and it
was just deleting the stored data.

Are you trying to draw a complex geometry? If it's just made out of basic
shapes you can use the Cstbrick.m, Cstcylinder.m and CstSphere.m to draw it
and then go with CstAdd.m and CstSubtract.m to do the adjustments. No need
for Picks, use geometry coordinates. If you want to make a more gaussian
style shape, I remember seeing in a youtube video that there was a
functionality in CST that draws a geometry by using the function that
describes it. Not sure how to do it, it should be interesting thought to
have such an .m function in the API
thanks
Simos

**Comment by SantaTitular** [comment]
Hi Simos,

Regarding the delete/results may be incomplete window (Maybe this is helpful for someone afterwards):

I tried to find more information and read other existing code, for instance the [link ](https://www.mathworks.com/matlabcentral/fileexchange/67731-hgiddenss-cst_app?tab=discussions), and it seems it is a new "feature" of recent versions of CST. As it is said in the discussion, alot of people encounter it, as end up stuck in the window like me. Anyways, besides the workaround suggested in the forum (use invoke('DeleteResults') before building new geometry), I found that you can also utilize invoke('Rebuild') to clear any existing geometries. The latter only requires that you re-do the solver parameters.

Regarding the complex geometry:

Yes! I have a rather complex surface (gaussian style as you said) that I generate in Matlab and I'm trying to figure how what is the best solution to "import it" in CST. I already tried building with bricks, cylinders, and spheres, but it is unfeasible and very very challenging. I also agree that it would be very interesting to have an .m function like that in the API, I'll try to find a video and think about one, we can try merging with your current API if you're still interested. If you happen to discover or find a way lemme know!

Best,
Tomás
