### ISSUE TITLE
How can I read message inforamtion in CST?

### ISSUE THREAD

**Issue by asong2001** [simos421/CST-MATLAB-API#4]
Thank you for your work in this project! It is useful for me to design antenna in CST. 

May I ask how can I read the message in MATLAB from CST? I am using CMA which is using Integraal Equation Solver to find Renonsance Frequency. This frequency will be shown in CST Messages window.

Thanks again for your work!

**Comment by simos421** [comment]
hmm I dont think that it is possible to read the CST messages info in Matlab because they are not included in the VBA script that runs in the CST background. You can write matlab script only with stuff that appear in the VBA script
