### ISSUE TITLE
It is possible to make polygons?

### ISSUE THREAD

**Issue by nirogiovanni** [simos421/CST-MATLAB-API#5]
Hi, 
congratulations for yours API,they helped me so much for my work.
I have to questions:
the first: i should use the polygon function, and i need to import the coordinates of the points composing the polygon from an external file, is there any way to do this through the VBA script? 
the second: i need to export the data about the maximum value of the gain vs frequencies, is there any way to do this as well? thank you.

**Comment by simos421** [comment]
Hi, thanks! 
Regarding your first question: The code is written in matlab, you can write a matlab script that reads your external file and use it as an input to my polygon function
for the second: just use the CstExportFarfieldSource for the frequency range that you want and then extract the max gain from the returned matrix
