### ISSUE TITLE
Plotting the S1,1 in Matlab

### ISSUE THREAD

**Issue by hisyammazmi** [simos421/CST-MATLAB-API#7]
Hello, I was running the microstrip example and Matlab returned these errors after the simulation is done in CST

![image](https://user-images.githubusercontent.com/74221351/119527066-2ce18800-bdaa-11eb-88b8-6590994d99b6.png)

I have not changed any parameters and lines, any idea what might caused it?

Best regards,

Hisyam

**Comment by simos421** [comment]
Yes check if you changed all the paths to folders according to your
computer's paths
Br
Simos

**Comment by hisyammazmi** [comment]
yes it works now, thank you

and also when I tried to use my own parameters (like the width and length of the patch) and it rounds up the value, and I had to change the line in Cstbrick.m from int2str to num2str

Again, thank you for the code, it really helps!
