### ISSUE TITLE
How to create lumped element

### ISSUE THREAD

**Issue by colinnnq** [simos421/CST-MATLAB-API#8]
Hi,

Is it possible to add a function for lumped elements in CST using matlab? 
When I try to use the following code to create a new lumped element,  there is an error in the line "invoke(LumpedElement, 'Create')".

function CstLumpedElement(mws,SetName,FolderName,C_value,SetP1,SetP2)
    LumpedElement = invoke(mws,'LumpedElement');
    invoke(LumpedElement,'Reset');
    invoke(LumpedElement,'SetName',int2str(SetName));    
    invoke(LumpedElement,'Folder',FolderName);
    invoke(LumpedElement,'SetType','RLCSerial');
    invoke(LumpedElement,'SetR','0');
    invoke(LumpedElement,'SetL','0');
    invoke(LumpedElement,'SetC',int2str(C_value));
    invoke(LumpedElement,'SetGs','0');
    invoke(LumpedElement,'SetI0','1e-14');
    invoke(LumpedElement,'SetT','300');
    invoke(LumpedElement,'SetP1','False',int2str(SetP1(1)),int2str(SetP1(2)),int2str(SetP1(3)));
    invoke(LumpedElement,'SetP2','False',int2str(SetP2(1)),int2str(SetP2(2)),int2str(SetP2(3)));
    invoke(LumpedElement,'SetInvert','False');
    invoke(LumpedElement,'SetMonitor','True');
    invoke(LumpedElement,'SetRadius','0.0');
    invoke(LumpedElement,'Wire','');
    invoke(LumpedElement,'Position','end1');
    invoke(LumpedElement,'CircuitFileName','');
    invoke(LumpedElement,'CircuitId','1');
    invoke(LumpedElement,'UseCopyOnly','True');
    invoke(LumpedElement,'UseRelativePath','False');
    invoke(LumpedElement,'Create');   
end

**Comment by simos421** [comment]
Hello,

There is no such function in my code at the moment, but you can make your
own lumped element function, it is easier than it seems.
The steps to do that are:

1) first design what you want in CST, without using matlab
2) then, if you open the history log of CST you will see that it records
everything you did in visual basic script
3) Now you need to interface this script with matlab. So open one of my
functions (e.g. anything in the home folder of the api) and see how I
translate tha visual basic script into a matlab function. I use the invoke
function in matlab to do the visual basic to matlab translation.
It might look intimidating but it is very easy. Mostly just copy-paste

To solve the error that you get in *"invoke(LumpedElement, 'Create')" *
just copy paste the way I did it in other m functions, most probably it's
some sort of syntax error

Br
Simos

**Comment by wang11de1fdfgdgadf** [comment]
@colinnnq Hi, bro. So, do you understand why there is an error here?
