### ISSUE TITLE
Add Support for Optimizer Calls

### ISSUE THREAD

**Issue by Sumalyo** [simos421/CST-MATLAB-API#9]
Adding support to the optimizers in CST would be really helpful

**Comment by simos421** [comment]
Hello ,

There is no such function in my code at the moment, but you can make your
own, it is easier than it seems.
The steps to do that are:

1) first use the optimizers within the CST environment, without
using matlab
2) then, if you open the history log of CST you will see that it records
everything you did in visual basic script
3) Now you need to interface this script with matlab. So open one of my
functions (e.g. anything in the home folder of the api) and see how I
translate tha visual basic script into a matlab function. I use the invoke
function in matlab to do the visual basic to matlab translation.
It might look intimidating but it is very easy. Mostly just copy-paste

Br
Simos
